### PR TITLE
Add ejecta.fileExists

### PR DESCRIPTION
**Pull request by finscn**
Add ejecta.fileExists(path)  for detecting  if a file exists. (sync).

example : 
```
if (!ejecta.fileExists("../../Documents/customIcon.jpg")) {
   // tell player upload a customIcon.jpg to Document Folder
}

```

see #460

### CODE REVIEW

**Comment by phoboslab** [comment]
As I said in #460, you can solve this in JS. I don't see the need for another native function that does the same thing.

```javascript
var fileExists = function(url) {
	var request = new XMLHttpRequest();
	request.open('GET', url, false); // sync
	request.send();
	return (request.status === 200);
};```

**Comment by finscn** [comment]
@phoboslab , I think ajax is not a good choice.

when I do sth like this:
```
if  ( fileExists( BigFile ) ) {
   load( BigFile );
}
```
if use ajax, it will try to load the file twice.  That wastes time and memory.

**Comment by phoboslab** [comment]
Well then load it once via Ajax and if loading fails you know the file doesn't exist :)

**Comment by finscn** [comment]
@phoboslab   I mean if file exist , it will be load(read)  twice.

**Comment by phoboslab** [comment]
Why?

```javascript
var request = new XMLHttpRequest();
request.open('GET', url, false); // sync
request.send();
if( request.status === 200 ) {
	doSomething(request.response);
}
else {
	// file does not exist
}
```
I understand that a dedicated `fileExists` method may be easier to use in your case, but I'm trying hard to not implement too many features in Ejecta that don't exist in browsers, especially when there are ways to do the same thing without another function.

**Comment by finscn** [comment]
if the file is js or image ,   the doSomething function hard to handle request.response.
I have to : 
```
if( request.status === 200 ) {
    var img= new Image();
    img.src=url;
    img.onload= .... ;
}
```

**Comment by phoboslab** [comment]
With https://github.com/phoboslab/Ejecta/commit/947f5b67091e9aa3197e7addb6470f758e90ea38 the onerror callback will fire if the file does not exist, even if the image will be lazily loaded

```javascript
var img = new Image();
img.src = url;
img.onload = function() { /* file exists * / }
img.onerror = function() { /* file does not exist * / }
```

**Pull request closed without merging**
