### PR TITLE
add tagName to mock HTMLElement

### PR DESCRIPTION
**Pull request by finscn**
some lib use  dom.tagName to detect dom type.

### CODE REVIEW

**Comment by finscn** [comment]
you could search some famous js framework /library , the  tagName is used more than nodeType . I hope this PR could be merged

**Comment by finscn** [comment]
nodeName is a property defined in the Node interface
http://www.w3.org/TR/DOM-Level-3-Core/core.html#ID-F68D095

tagName is a property defined in the Element interface
http://www.w3.org/TR/DOM-Level-3-Core/core.html#ID-104682815

To check a node whether a HTMLElement , the better way is use tagName.
If use nodeName , We will hard to differentiate  XMLNode(XML island inHTML) and HTMLElement.

```
<html>
   <canvas></canvas>     ----> A
   <xml>
      <canvas></canvas>   -----> B
 </xml>

</html>
```

A is HTMLElement , B is Not.

And document.getElementByTagName also find elements    by  tagName.

So ,   the Web/HTML/JS  Developers  are more used to  tagName.

**Comment by finscn** [comment]
And Web developers also could use     ```if (element.tagName)``` to check it's whether a valid node (not text , not attribute ,not comment).

**Comment by phoboslab** [comment]
You're right. I'm just wary of bloat. I fear we might end up with Browser if keep supporting everything a Browser supports. I'm still not sure where to draw the line, especially with these "mock" HTML Elements.

**Comment by jmo84** [comment]
@finscn 

You should be able to define tagName for HTMLElement using JavaScript without touching Ejecta's Objective-C code.

That being said, why do you need to use getElementsByTagName for a game? You can already reference the main canvas that Ejecta creates for you.

**Pull request merged**
